### ISSUE TITLE
How to override Quality Definitions for specific profile?

### ISSUE THREAD

**Issue by zey0n** [recyclarr/config-templates#119]
How do we override Quality Definition for specific profiles like _Bluray-1080p_, and specify custom min, preferred, max values?

Here is my custom template:
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

###################################################################################################
# Merged Templates [UHD Bluray + WEB] + [HD Bluray + WEB]                                         #
#                                                                                                 #
# Recyclarr Configuration Template: UHD Bluray + WEB                                              #
# (Prefers x265)                                                                                  #
# Updated: 2025-FEB-12                                                                            #
#                                                                                                 #
# Recyclarr Configuration Template: HD Bluray + WEB                                               #
# (Prefers x265)                                                                                  #
# Updated: 2025-FEB-12                                                                            #
#                                                                                                 #
# Manual Configuration Template: HD 264 Bluray + WEB                                              #
# (Prefers h.264 over 265)                                                                        #
# Updated: 2025-FEB-12                                                                            #
###################################################################################################
radarr:
  radar-uhd-hd:
    base_url: http://removed:7878
    api_key: removed
        
        
    # Media Naming Configuration
    media_naming:
      folder: default # Use TRaSH Guide default suggestion
      movie:
        rename: true
        standard: default # Use TRaSH Guide default suggestion


    # Quality (File Size)
    quality_definition:
      type: movie # Use Default Quality Definations


    # TRaSH Templates
    include:
      # Quality Defination
      - template: radarr-quality-definition-movie
      
      # Movies UHD (Profile, Formats)
      - template: radarr-quality-profile-uhd-bluray-web
      - template: radarr-custom-formats-uhd-bluray-web
      
      # Movies HD (Profile, Formats)
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web


    # Profiles
    quality_profiles:
      # UHD Profile - Already included from templates
      # HD Profile - Already included from templates
      
      # HD Profile (Block H265) - Manual (Copied from Existing template of 'HD Bluray + WEB')
      - name: HD 264 Bluray + WEB
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: Bluray-720p


    # Always delete old unused formats, and overwrite existing formats
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # Custom Format Configuration
    custom_formats:
       
      # Prefer Original Audio
      - trash_ids:
          - custom-original-language # Prefer Original Language
        assign_scores_to:
          - name: UHD Bluray + WEB
          - name: HD Bluray + WEB
          - name: HD 264 Bluray + WEB

      # Audio
      - trash_ids:
          # Enable Advanced Audio Formats (Applicable to all profiles)
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
          - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          - 3cafb66171b47f226146a0770576870f # TrueHD
          - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          - e7c2fcae07cbada050a0af3357491d7b # PCM
          - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          - 185f1dd7264c4562b9022d963ac37424 # DD+
          - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          - 240770601cc226190c367ef59aba7463 # AAC
          - c2998bd0d90ed5621d8df281e839436e # DD
        assign_scores_to:
          - name: UHD Bluray + WEB
          - name: HD Bluray + WEB
          - name: HD 264 Bluray + WEB

      # Movie Versions
      - trash_ids:
          # Prefer these movie versions (Applicable to all profiles)
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: UHD Bluray + WEB
          - name: HD Bluray + WEB
          - name: HD 264 Bluray + WEB


      # Block Bad Releases (Applicable to all profiles)
      - trash_ids:
           - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
           - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
           #- ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
           - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
           #- 5c44f52a8714fdd79bb4d98e2673be1f # Retags
           - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: UHD Bluray + WEB
          - name: HD Bluray + WEB
          - name: HD 264 Bluray + WEB


      # Allow x265 releases with HDR/Dolby-Vision (Applicable to UHD and HD)
      - trash_ids:
           - dc98083864ea246d05a42df0d05f81cc # Unblock 720/1080p (HD) releases that are encoded in x265
        assign_scores_to:
           - name: UHD Bluray + WEB
             score: 0 # Unblock by reseting score to 0
           - name: HD Bluray + WEB
             score: 0 # Unblock by reseting score to 0
      - trash_ids:
           - 839bea857ed2c0a8e084f3cbdbd65ecb # Blocks 720/1080p (HD) releases that are encoded in x265, But allow 720/1080p x265 releases if they have HDR and/or DV
        assign_scores_to:
          - name: UHD Bluray + WEB
          - name: HD 264 Bluray + WEB


      # Allow any x265 release (Applicable only for HD)
      - trash_ids:
           - 9170d55c319f4fe40da8711ba9d8050d # x265 (any)
        assign_scores_to:
          - name: HD Bluray + WEB
            score: 100


      # Allow with Dolby-Vision/HDR+ (Applicable only for UHD)
      - trash_ids:
          - b17886cb4158d9fea189859409975758 # HDR10Plus Boost
          - 55a5b50cb416dea5a50c4955896217ab # Dolby-Vision HDR10+ Boost
        assign_scores_to:
          - name: UHD Bluray + WEB


      # Block SDR (exclude WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
           - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: UHD Bluray + WEB
```
