### ISSUE TITLE
Unable to find config template 'radarr-quality-definition-anime'

### ISSUE THREAD

**Issue by darkylein** [recyclarr/config-templates#130]
I inlcuded [radarr-quality-definition-anime](https://github.com/recyclarr/config-templates/blob/9eb539ba72fafd98ee65c737a9ba2c26ce75a29a/radarr/includes/quality-definitions/radarr-quality-definition-anime.yml) like here:

```yaml
include:
  - template: radarr-custom-formats-anime
  - template: radarr-quality-definition-anime
  - template: radarr-quality-profile-anime
```

Other templates work fine, but this one does not. I get this error:

```text
[INF] Console Output Settings {"RawOption":null,"NoColor":false,"IsTerminal":true}
[INF] Config Templates Repo: Cloning...
[INF] Trash Guides Repo: Cloning...
[ERR] Exiting due to fatal error: For service type 'Radarr', unable to find config template with name 'radarr-quality-definition-anime'
ERROR: 1
```

When I add the quality definition manually it does not work either.

I've can replicate this with the latest and edge image tag on docker.
