### ISSUE TITLE
Use file name as instance name in all templates

### ISSUE THREAD

**Issue by rcdailey** [recyclarr/config-templates#19]
I think it would be a good idea to have a unique instance name (by default) in every configuration file. Specifically, I think the instance name should follow the file name. This has a few benefits:

- It's easier to identify the instances you can run by looking at the file names.
- It's one less manual edit users have to make.
- If users want to merge instances into a single file, that becomes easier too.

As an example, if we look at `radarr/uhd-bluray-web.yml`:

```yml
# Updated: 2023-07-19
radarr:
  radarr:  # A custom name used to identify this particular instance.
    base_url: Put your Radarr URL here
    api_key: Put your API key here
```

I propose that we rename the instance (for this one file) to `uhd-bluray-web`, like so:

```yml
# Updated: 2023-07-19
radarr:
  uhd-bluray-web:  # A custom name used to identify this particular instance.
    base_url: Put your Radarr URL here
    api_key: Put your API key here
```

How does this sound to you @yammes08?
